# Example ESPHome configuration for Gree AC
# Place this component folder in your ESPHome config directory as:
# esphome/components/gree_ac/

esphome:
  name: gree-ac

esp32:
  board: esp32dev
  framework:
    type: arduino

# Local components are adjacent to this YAML (keep `components/` next to this file)

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0  # Disable logging over UART

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: "your-ota-password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot
  ap:
    ssid: "Gree AC Fallback"
    password: "fallback-password"

# UART configuration for Gree AC
# Connect:
#   ESP TX -> AC RX (pin 2 on AC connector)
#   ESP RX -> AC TX (pin 3 on AC connector) - use voltage divider 5V -> 3.3V
#   ESP GND -> AC GND (pin 4)
#   ESP VIN -> AC 5V (pin 1)
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 4800
  parity: EVEN
  data_bits: 8
  stop_bits: 1

external_components:
  - source: components

# Main climate component
climate:
  - platform: gree_ac
    id: my_gree_ac
    name: "Living Room AC"
    update_interval: 5s
    supported_presets:
      - NONE
      - BOOST
    supported_swing_modes:
      - "OFF"
      - VERTICAL
      - HORIZONTAL
      - BOTH

    # Optional: Use external temperature sensor instead of AC's sensor
    # current_temperature_sensor: external_temp_sensor
    
    # Optional features like advanced swing, display and switches
    # were removed from this component to simplify compilation.
    # Re-add them later via a controlled incremental implementation.

# Optional: External temperature sensor (Dallas DS18B20)
# one_wire:
#   - platform: gpio
#     pin: GPIO4
# 
# sensor:
#   - platform: dallas_temp
#     name: "Room Temperature"
#     id: external_temp_sensor
#     address: 0x1234567890abcdef

# Optional: Monitor WiFi signal
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# Optional: Status LED
status_led:
  pin:
    number: GPIO2
    inverted: true

